const B={GCP:[
["Which service runs containers without managing servers?",["Cloud Run","Compute Engine","Cloud SQL","BigQuery"],0,"Cloud Run is fully managed container execution.","https://cloud.google.com/run/docs"],
["Which IAM role gives read access to Cloud Storage objects? ",["Storage Admin","Storage Object Viewer","Owner","Editor"],1,"Storage Object Viewer is a narrow read role.","https://cloud.google.com/storage/docs/access-control/iam-roles"],
["What is a GKE node pool?",["A group of similarly configured nodes","A database","A registry","A namespace"],0,"A node pool groups nodes with common configuration.","https://cloud.google.com/kubernetes-engine/docs/concepts/node-pools"],
["Which service is a managed relational database?",["Cloud SQL","BigQuery","Pub/Sub","Filestore"],0,"Cloud SQL supports managed relational engines.","https://cloud.google.com/sql/docs"],
["Which service provides asynchronous messaging?",["Pub/Sub","Cloud DNS","Cloud CDN","Filestore"],0,"Pub/Sub provides asynchronous messaging.","https://cloud.google.com/pubsub/docs"],
["What does Workload Identity Federation help avoid?",["Long-lived service-account keys","VPCs","Containers","DNS"],0,"Federation lets workloads authenticate without storing long-lived keys.","https://cloud.google.com/iam/docs/workload-identity-federation"],
["Which service is optimized for analytical SQL?",["BigQuery","Cloud SQL","Firestore","Filestore"],0,"BigQuery is Google's analytical data warehouse.","https://cloud.google.com/bigquery/docs"],
["What does Terraform provide?",["Infrastructure as Code","A container runtime","A message broker","A DNS server"],0,"Terraform manages infrastructure declaratively as code.","https://developer.hashicorp.com/terraform/docs"]
],CKA:[
["Which command lists Pods in every namespace?",["kubectl get pods -A","kubectl list pods","kubectl get all -n all","kubectl pods"],0,"-A means all namespaces.","https://kubernetes.io/docs/reference/kubectl/"],
["Which object gives Pods a stable network endpoint?",["Service","ConfigMap","Secret","Job"],0,"A Service provides a stable virtual endpoint.","https://kubernetes.io/docs/concepts/services-networking/service/"],
["What happens when readiness fails?",["Pod is removed from Service endpoints","Node is deleted","Image is deleted","Namespace is deleted"],0,"Unready Pods do not receive Service traffic.","https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/"],
["Which object stores non-sensitive configuration?",["ConfigMap","Secret","ServiceAccount","Role"],0,"ConfigMaps hold non-confidential configuration.","https://kubernetes.io/docs/concepts/configuration/configmap/"],
["Which resource maintains desired replicas for a stateless app?",["Deployment","Service","Ingress","Namespace"],0,"Deployments manage ReplicaSets and desired Pods.","https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"],
["What does a PersistentVolumeClaim request?",["Storage","A Pod","An IP","An IAM role"],0,"PVCs request storage with defined characteristics.","https://kubernetes.io/docs/concepts/storage/persistent-volumes/"],
["Which command is useful for troubleshooting events?",["kubectl get events","kubectl get images","kubectl show events","kubectl events"],0,"Events reveal scheduling and runtime problems.","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_get/kubectl_get_events/"],
["What is a namespace mainly for?",["Logical isolation and organization","Encryption","Image building","Node scaling"],0,"Namespaces organize and isolate namespaced resources.","https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"]
],CKAD:[
["Which probe determines if a container should receive traffic?",["Readiness","Liveness","Startup","Node"],0,"Readiness controls whether a Pod receives traffic.","https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/"],
["Which object injects key-value configuration?",["ConfigMap","Service","Ingress","PV"],0,"ConfigMaps can be consumed as environment variables or files.","https://kubernetes.io/docs/concepts/configuration/configmap/"],
["Which command creates a deployment named web using nginx?",["kubectl create deployment web --image=nginx","kubectl deploy web nginx","kubectl new web nginx","kubectl run deployment web"],0,"The create deployment command creates the Deployment.","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_deployment/"],
["What does a Service selector do?",["Selects Pods for traffic","Deletes nodes","Selects namespaces","Selects images"],0,"Selectors identify backend Pods.","https://kubernetes.io/docs/concepts/services-networking/service/"],
["Which field specifies a container image?",["image","containerImage","runtime","artifact"],0,"The containers spec uses image.","https://kubernetes.io/docs/concepts/containers/images/"],
["What are resource requests used for?",["Scheduling and expected capacity","DNS","External exposure","Secrets"],0,"Requests influence scheduling and reserve expected capacity.","https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/"],
["Which workload runs a task to completion?",["Job","Deployment","DaemonSet","Service"],0,"Jobs run Pods until successful completion.","https://kubernetes.io/docs/concepts/workloads/controllers/job/"],
["Which object is intended for sensitive values?",["Secret","ConfigMap","Service","Namespace"],0,"Secrets are designed for sensitive data.","https://kubernetes.io/docs/concepts/configuration/secret/"]
]};
var cert=null,qs=[],ans=[],i=0,t=2700,timer;
function sh(s){return String(s).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function home(){document.getElementById("app").innerHTML='<header><b>⚡ CertPulse</b><small>FREE MOCK EXAMS</small></header><main><div class="eyebrow">CLOUD CERTIFICATION PREP</div><h1>Practice like the real exam.<br><span>Understand every answer.</span></h1><p class="lead">Free timed practice for cloud engineers, with explanations and official documentation links.</p><div class="cards">'+Object.keys(B).map(function(k){return '<button class="card" onclick="start(\''+k+'\')"><strong>'+(k==="GCP"?"☁️ ":"◈ ")+(k==="GCP"?"Google Cloud Associate Cloud Engineer":"Kubernetes "+k)+'</strong><em>20 questions · 45 min</em><b>Start mock exam →</b></button>'}).join("")+'</div><p class="note">✓ Original practice questions · ✓ Official docs · ✓ No exam dumps</p></main>'}
function start(c){cert=c;qs=B[c].slice().sort(function(){return Math.random()-.5});ans=[];i=0;t=2700;clearInterval(timer);timer=setInterval(function(){t--;if(t<=0){clearInterval(timer);review()}else{render()}},1000);render()}
function render(){var q=qs[i];document.getElementById("app").innerHTML='<header><b>⚡ CertPulse</b><strong>⏱ '+Math.floor(t/60).toString().padStart(2,"0")+":"+String(t%60).padStart(2,"0")+'</strong></header><main class="exam"><div class="meta">'+(cert==="GCP"?"Google Cloud ACE":"Kubernetes "+cert)+' <span>Question '+(i+1)+' / '+qs.length+'</span></div><div class="bar"><i style="width:'+((i+1)/qs.length*100)+'%"></i></div><section><div class="eyebrow">MOCK EXAM</div><h2>'+sh(q[0])+'</h2><div class="opts">'+q[1].map(function(x,j){return '<button class="'+(ans[i]===j?"sel":"")+'" onclick="choose('+j+')"><span>'+String.fromCharCode(65+j)+'</span>'+sh(x)+'</button>'}).join("")+'</div></section><nav><button onclick="prev()" '+(i?"":"disabled")+'>← Previous</button><button class="primary" onclick="'+(i===qs.length-1?"review()":"next()")+'">'+(i===qs.length-1?"Submit exam":"Next →")+'</button></nav></main>'}
function choose(j){ans[i]=j;render()}function next(){if(i<qs.length-1)i++;render()}function prev(){if(i)i--;render()}
function review(){clearInterval(timer);var score=0;qs.forEach(function(q,n){if(ans[n]===q[2])score++});document.getElementById("app").innerHTML='<header><b>⚡ CertPulse</b><button onclick="home()">New exam</button></header><main class="review"><div class="score"><div class="circle">'+Math.round(score/qs.length*100)+'%</div><div><div class="eyebrow">RESULT</div><h1>'+score+'/'+qs.length+' correct</h1><p>Review every explanation and revisit the docs.</p></div></div>'+qs.map(function(q,n){return '<article class="'+(ans[n]===q[2]?"ok":"bad")+'"><small>Q'+(n+1)+'</small><h3>'+sh(q[0])+'</h3><p><b>Your answer:</b> '+sh(q[1][ans[n]]||"Not answered")+'</p><p><b>Correct:</b> '+sh(q[1][q[2]])+'</p><p>'+sh(q[3])+'</p><a target="_blank" href="'+q[4]+'">Read official docs ↗</a></article>'}).join("")+'</main>'}
home();